export const keywords = [
  "React",
  "ReactDOM",
  "createRoot",
  "createElement",
  "npm",
  "package.json",
  "package-lock.json",
  "Dependencies",
  "Dev Dependencies",
  "Bundler",
  "Parcel",
  "Caret & Tilde",
  "npx",
  "Hot Module Replacement",
  "File Watching Algorithm",
  "Image Optimization",
  "Consistent Hashing",
  "Differential Bundling",
  "Diagnostics",
  "Tree Shaking",
  "browserList",
  "build",
  "React Elements",
  "JSX",
  "Transpiler",
  "Babel",
  "Components",
  "Class Component",
  "Functional Component",
  "Component Composition",
  "Props",
  "Config Driven UI",
  "Hooks",
  "Import & Export",
  "Utils",
  "useState()",
  "state variable",
  "Reconciliation Algorithm(React Fiber)",
  "Diff Algorithm",
  "Virtual DOM",
  "Incremental Rendering",
  "Monolith Architecture",
  "Microservice Architecture",
  "Separation of concerns",
  "Single Responsibility Principle",
  "useEffect()",
];