export const keywords = [
  "React",
  "ReactDOM",
  "createRoot",
  "createElement",
  "npm",
  "package.json",
  "package-lock.json",
  "Dependencies",
  "Dev Dependencies",
  "Bundler",
  "Parcel",
  "Caret",
  "Tilde",
  "npx",
  "Hot Module Replacement",
  "File Watching Algorithm",
  "Image Optimization",
  "Consistent Hashing",
  "Differential Bundling",
  "Diagnostics",
  "Error Handling",
  "Tree Shaking",
  "browserList",
  "build",
  "React Elements",
  "JSX",
  "Transpiler",
  "Babel",
  "Components",
  "Class Compoenent",
  "Functional Compoenent",
  "Component Composition",
  "Cross-side Scripting",
  "Props",
  "Config Driven UI",
  "Hooks",
  "Import",
  "Export",
  "Utils",
  "useState()",
  "Reconciliation Algorithm",
  "React Fiber",
  "Diff Algorithm",
  "Virtual DOM",
  "Incremental Rendering",
  "Monolith Architecture",
  "Microservice Architecture",
  "Separation of concerns",
  "Single Responsibility Principle",
  "useEffect()",
  "CORS",
  "Optional Chaining",
];